import sys
sys.path.append('../../../site_scons')

import lib_helper

LIBS = ['SDL2', 'SDL2_ttf', 'SDL2_image',
        'boost_timer', 'boost_filesystem', 'boost_system', 'boost_thread', 'boost_python',
        'stdc++', 'pthread', 'dl'
        ]

root = Dir('../../../').abspath



src = root+'/src'



def make_loader(file):
    sources = [
        './loaders/'+file+'.cpp',
        './Loader.cpp',
        './WorldLoader.cpp',
    ]
    lib_helper.make_shared(file, sources, 'bin/loaders', LIBS)


LOADERS = ['LoaderDummy', 'LoaderXML', 'LoaderMD2', 'TextureLoader', 'XMLWorldLoader', 'SquareWorldLoader' ]

for l in LOADERS:
    make_loader(l)
