root = '../../'
env = Environment(CPPPATH=[
    '/usr/include/python2.7',
    '/usr/include/bullet',
    root + '/hpp',
])

src = root+'/src'

env['SHLIBPREFIX'] = ''

l_shared_env.SharedLibrary('./bin/loaders/LoaderDummy', [

    root+'src/cpp/loaders/LoaderDummy.cpp',
    root+'src/cpp/loaders/Loader.cpp',
],
                         LIBS=LIBS,
                         LIBPATH='.'
)

l_shared_env.Append(LINKFLAGS=['-Wl,-soname,LoaderDummy.so'])