import sys
sys.path.append('../../../site_scons')

import lib_helper

LIBS = ['stdc++', 'pthread', 'dl', 'GL', 'GLEW', 'GLU' ]

def make_renderer(file, subdir):
    sources = [
        './rendererAbstract.cpp',
        subdir+'/'+file+'.cpp'
    ]
    lib_helper.make_shared(file, sources, 'bin', LIBS)



renderers = {'GL': 'rendererGL', 'GL': 'RendererOpenGL'}

for subdir in renderers:
    make_renderer(renderers[subdir], subdir)