import sys
sys.path.append('../../../site_scons')

import lib_helper
from common_flags import *


LIBS = ['stdc++', 'pthread', 'dl', 'GL', 'GLEW', 'GLU' ] + ROCKET_LIBS

def make_renderer(file, subdir):
    sources = [
        subdir+'/'+file+'.cpp'
    ]
    lib_helper.make_shared(file, sources, 'bin', LIBS)



renderers = { 'GL': 'RendererOpenGL'}


for subdir in renderers:
    make_renderer(renderers[subdir], subdir)